In [8]:
# Task 1 creating dataframe and save in csv 

# import python libraries 
import pandas as pd 
import numpy as np
from IPython.display import display
# creating project dataframe using pandas dictionary 
project_data = {
    "ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"],
    "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5","Project 6","Project 7","Project 8","Project 9","Project 10","Project 11","Project 12","Project 13","Project 14"],
    "Cost": [1002000,2000000,4500000,5500000,np.nan,680000,400000,350000,np.nan,300000,2000000,1000000,3000000,200000],
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished","Failed","Ongoing","Finished","Failed","Ongoing","Finished","Finished"]
}

# creating employee dataframe
employee_data={
 "ID":["A001","A002","A003","A004","A005"],
 "Name": ["John Alter","Alice Luxemburg","Tom Sabestine","Nina Adgra","Amy Johny"],
 "Gender":["M","F","M","F","F"],
 "City":["Paris","London","Berlin","Newyork","Madrid"],
 "Age" :[25,27,29,31,30]
}
# convert employeedata into dataframe
employee_df = pd.DataFrame (employee_data).set_index("ID")
employee_df.to_csv("employee.csv",index=False) # employee data


 # saving employeefile in csv format
 #  employee_df.to_csv("employee.csv",index='False') # employee data

# creating Seniority Level DataFrame
seniority_data = {
    "ID":["A001","A002","A003","A004","A005"],
    "Designation Level":[2,2,3,2,3]
}

# convert projectdata into dataframe
project_df = pd.DataFrame(project_data).set_index("ID")
# convert senioritylevel into  dataframe
seniority_df = pd.DataFrame (seniority_data).set_index("ID")

# saving all 3 _data file in csv format 
project_df.to_csv("project.csv", index=True) # project data
employee_df.to_csv("employee.csv",index=True) # employee data
seniority_df.to_csv ("seniority.csv",index=True) # seniority data



# display project output
print ("project_dataframe:")
display(project_df)

# display employee output
print ("employee_dataframe:") 
display (employee_df)

# display seniority output
print ("Seniority_dataframe:")
display (seniority_df)

project_dataframe:

         Project       Cost    Status
ID
A001   Project 1  1002000.0  Finished
A002   Project 2  2000000.0   Ongoing
A003   Project 3  4500000.0  Finished
A004   Project 4  5500000.0   Ongoing
A005   Project 5        NaN  Finished
A002   Project 6   680000.0    Failed
A005   Project 7   400000.0  Finished
A003   Project 8   350000.0    Failed
A001   Project 9        NaN   Ongoing
A003  Project 10   300000.0  Finished
A001  Project 11  2000000.0    Failed
A004  Project 12  1000000.0   Ongoing
A004  Project 13  3000000.0  Finished
A005  Project 14   200000.0  Finished

employee_dataframe:

                 Name Gender     City  Age
ID
A001       John Alter      M    Paris   25
A002  Alice Luxemburg      F   London   27
A003    Tom Sabestine      M   Berlin   29
A004       Nina Adgra      F  Newyork   31
A005        Amy Johny      F   Madrid   30

Seniority_dataframe:

      Designation Level
ID
A001                  2
A002                  2
A003                  3
A004                  2
A005                  3

In [9]:
# task 2  find and Replace the missing values by running average

import pandas as pd
from IPython.display import display

# Load Project CSV
project_df = pd.read_csv("Project.csv")

# Initialize empty list to store running average
running_avg = []

# Initialize sum and count
total = 0
count = 0

# use loop in a row
for i in range(len(project_df)):
    
    # If value is not null
    if not pd.isna(project_df.loc[i, "Cost"]):
        total += project_df.loc[i, "Cost"]  # Add cost
        count += 1  # Increase count
        running_avg.append(project_df.loc[i, "Cost"])  # Keep original value
    
    else:
        avg = total / count  # Calculate running average
        running_avg.append(avg)  # Replace missing value

# Replace Cost column
project_df["Cost"] = running_avg

# Save updated file

project_df.set_index("ID", inplace=True)
project_df.to_csv("Project.csv", index=True)

# Display output
print ("project_df:")
display (project_df)

project_df:

         Project          Cost    Status
ID
A001   Project 1  1.002000e+06  Finished
A002   Project 2  2.000000e+06   Ongoing
A003   Project 3  4.500000e+06  Finished
A004   Project 4  5.500000e+06   Ongoing
A005   Project 5  3.250500e+06  Finished
A002   Project 6  6.800000e+05    Failed
A005   Project 7  4.000000e+05  Finished
A003   Project 8  3.500000e+05    Failed
A001   Project 9  2.061714e+06   Ongoing
A003  Project 10  3.000000e+05  Finished
A001  Project 11  2.000000e+06    Failed
A004  Project 12  1.000000e+06   Ongoing
A004  Project 13  3.000000e+06  Finished
A005  Project 14  2.000000e+05  Finished

In [10]:
# task 3 split the column into two parts and remove the older name column

# import libraries
import pandas as pd 

# load the employee csv files
employee_df =pd.read_csv("employee.csv").set_index("ID")

# split firstname and last name
employee_df [["FirstName","LastName"]]=employee_df["Name"].str.split(" ",expand=True)

# Drop original Name column
employee_df.drop("Name", axis=1, inplace=True)

employee_df = employee_df[["FirstName", "LastName", "Gender","City", "Age"]]

# Save updated CSV
employee_df.to_csv("employee1.csv", index=False)

# Display output
print ("new employeedata:")
display (employee_df)

new employeedata:

     FirstName   LastName Gender     City  Age
ID
A001      John      Alter      M    Paris   25
A002     Alice  Luxemburg      F   London   27
A003       Tom  Sabestine      M   Berlin   29
A004      Nina      Adgra      F  Newyork   31
A005       Amy      Johny      F   Madrid   30

In [11]:
# Task 4  Join all three dataframes in one single dataframe. Name it “Final

# import python libraries 
import pandas as pd
from IPython.display import display

# load all three  csv file 
project_df=pd.read_csv("Project.csv").set_index("ID")
employee_df=pd.read_csv("employee.csv").set_index("ID")
seniority_df=pd.read_csv ("seniority.csv").set_index("ID")

# Merge Project and Employee on 'ID'
df1 = pd.merge(project_df, employee_df, on="ID")   # Inner join

# Merge the above result with Seniority dataframe
Final = pd.merge(df1,seniority_df, on="ID")    # Final merged dataframe

# Display Final dataframe
print("Final DataFrame:")
display(Final)

Final DataFrame:

,Project,Cost,Status,Name,Gender,City,Age,Designation Level
ID,,,,,,,,
A001,Project 1,1.002000e+06,Finished,John Alter,M,Paris,25,2
A002,Project 2,2.000000e+06,Ongoing,Alice Luxemburg,F,London,27,2
A003,Project 3,4.500000e+06,Finished,Tom Sabestine,M,Berlin,29,3
A004,Project 4,5.500000e+06,Ongoing,Nina Adgra,F,Newyork,31,2
A005,Project 5,3.250500e+06,Finished,Amy Johny,F,Madrid,30,3
A002,Project 6,6.800000e+05,Failed,Alice Luxemburg,F,London,27,2
A005,Project 7,4.000000e+05,Finished,Amy Johny,F,Madrid,30,3
A003,Project 8,3.500000e+05,Failed,Tom Sabestine,M,Berlin,29,3
A001,Project 9,2.061714e+06,Ongoing,John Alter,M,Paris,25,2
A003,Project 10,3.000000e+05,Finished,Tom Sabestine,M,Berlin,29,3
A001,Project 11,2.000000e+06,Failed,John Alter,M,Paris,25,2
A004,Project 12,1.000000e+06,Ongoing,Nina Adgra,F,Newyork,31,2
A004,Project 13,3.000000e+06,Finished,Nina Adgra,F,Newyork,31,2
A005,Project 14,2.000000e+05,Finished,Amy Johny,F,Madrid,30,3

In [12]:
# Task 5 Add a new bonus column in the Final dataframe. Give a 5% bonus concerning project
#cost only to employees who have finished the projects

# import python libraries
import pandas as pd
from IPython.display import display
import numpy as np

# Create Bonus column based on condition
Final["Bonus"] = np.where(
    (Final["Status"] == "Finished") & (Final["Cost"].notna()),  # Condition
    Final["Cost"] * 0.05,  # 5% of cost
    0  # Otherwise 0
)

# Display updated dataframe
print("Final DataFrame with Bonus column:")
print(Final)

Final DataFrame with Bonus column:
         Project          Cost    Status             Name Gender     City  \
ID
A001   Project 1  1.002000e+06  Finished       John Alter      M    Paris
A002   Project 2  2.000000e+06   Ongoing  Alice Luxemburg      F   London
A003   Project 3  4.500000e+06  Finished    Tom Sabestine      M   Berlin
A004   Project 4  5.500000e+06   Ongoing       Nina Adgra      F  Newyork
A005   Project 5  3.250500e+06  Finished        Amy Johny      F   Madrid
A002   Project 6  6.800000e+05    Failed  Alice Luxemburg      F   London
A005   Project 7  4.000000e+05  Finished        Amy Johny      F   Madrid
A003   Project 8  3.500000e+05    Failed    Tom Sabestine      M   Berlin
A001   Project 9  2.061714e+06   Ongoing       John Alter      M    Paris
A003  Project 10  3.000000e+05  Finished    Tom Sabestine      M   Berlin
A001  Project 11  2.000000e+06    Failed       John Alter      M    Paris
A004  Project 12  1.000000e+06   Ongoing       Nina Adgra      F  Newyork
A004  Project 13  3.000000e+06  Finished       Nina Adgra      F  Newyork
A005  Project 14  2.000000e+05  Finished        Amy Johny      F   Madrid

      Age  Designation Level     Bonus
ID
A001   25                  2   50100.0
A002   27                  2       0.0
A003   29                  3  225000.0
A004   31                  2       0.0
A005   30                  3  162525.0
A002   27                  2       0.0
A005   30                  3   20000.0
A003   29                  3       0.0
A001   25                  2       0.0
A003   29                  3   15000.0
A001   25                  2       0.0
A004   31                  2       0.0
A004   31                  2  150000.0
A005   30                  3   10000.0

In [13]:
#task 6
#Demote the designation level by 1, whose projects have status “fail”. Delete the
#employees record whose designation level is above 4

# Import required libraries
import pandas as pd

# Load CSV files
project = pd.read_csv("Project.csv")       # Load Project data
employee = pd.read_csv("Employee.csv")     # Load Employee data
seniority = pd.read_csv("Seniority.csv")   # Load Seniority data

# Create Final DataFrame (Task 4)
df1 = pd.merge(project, employee, on="ID")        # Merge Project + Employee
Final = pd.merge(df1, seniority, on="ID")         # Merge with Seniority

# Task 6: Demote designation level where status is 'Failed'
Final.loc[Final["Status"] == "Failed", "Designation Level"] -= 1

# Delete employees whose designation level is above 4
Final = Final[Final["Designation Level"] <= 4]

# Display result
print("newDataframe:")
print(Final)

# Save to new CSV file
Final.to_csv("Final_Task6.csv", index=False)

newDataframe:
      ID     Project          Cost    Status             Name Gender     City  \
0   A001   Project 1  1.002000e+06  Finished       John Alter      M    Paris
1   A002   Project 2  2.000000e+06   Ongoing  Alice Luxemburg      F   London
2   A003   Project 3  4.500000e+06  Finished    Tom Sabestine      M   Berlin
3   A004   Project 4  5.500000e+06   Ongoing       Nina Adgra      F  Newyork
4   A005   Project 5  3.250500e+06  Finished        Amy Johny      F   Madrid
5   A002   Project 6  6.800000e+05    Failed  Alice Luxemburg      F   London
6   A005   Project 7  4.000000e+05  Finished        Amy Johny      F   Madrid
7   A003   Project 8  3.500000e+05    Failed    Tom Sabestine      M   Berlin
8   A001   Project 9  2.061714e+06   Ongoing       John Alter      M    Paris
9   A003  Project 10  3.000000e+05  Finished    Tom Sabestine      M   Berlin
10  A001  Project 11  2.000000e+06    Failed       John Alter      M    Paris
11  A004  Project 12  1.000000e+06   Ongoing       Nina Adgra      F  Newyork
12  A004  Project 13  3.000000e+06  Finished       Nina Adgra      F  Newyork
13  A005  Project 14  2.000000e+05  Finished        Amy Johny      F   Madrid

    Age  Designation Level
0    25                  2
1    27                  2
2    29                  3
3    31                  2
4    30                  3
5    27                  1
6    30                  3
7    29                  2
8    25                  2
9    29                  3
10   25                  1
11   31                  2
12   31                  2
13   30                  3

In [14]:
# Task 7 Add Mr./Mrs. and Drop Gender
# Import python libraries 
import numpy as np 
# Add prefix based on gender
Final["Name"] = np.where(
    Final["Gender"] == "M",        
    "Mr. " + Final["Name"],  
    "Mrs. " + Final["Name"]   
)
 #Drop Gender column
Final.drop("Gender", axis=1, inplace=True)

# Display updated dataframe
print("updatedDataframe1:")
print(Final)

updatedDataframe1:
      ID     Project          Cost    Status                  Name     City  \
0   A001   Project 1  1.002000e+06  Finished        Mr. John Alter    Paris
1   A002   Project 2  2.000000e+06   Ongoing  Mrs. Alice Luxemburg   London
2   A003   Project 3  4.500000e+06  Finished     Mr. Tom Sabestine   Berlin
3   A004   Project 4  5.500000e+06   Ongoing       Mrs. Nina Adgra  Newyork
4   A005   Project 5  3.250500e+06  Finished        Mrs. Amy Johny   Madrid
5   A002   Project 6  6.800000e+05    Failed  Mrs. Alice Luxemburg   London
6   A005   Project 7  4.000000e+05  Finished        Mrs. Amy Johny   Madrid
7   A003   Project 8  3.500000e+05    Failed     Mr. Tom Sabestine   Berlin
8   A001   Project 9  2.061714e+06   Ongoing        Mr. John Alter    Paris
9   A003  Project 10  3.000000e+05  Finished     Mr. Tom Sabestine   Berlin
10  A001  Project 11  2.000000e+06    Failed        Mr. John Alter    Paris
11  A004  Project 12  1.000000e+06   Ongoing       Mrs. Nina Adgra  Newyork
12  A004  Project 13  3.000000e+06  Finished       Mrs. Nina Adgra  Newyork
13  A005  Project 14  2.000000e+05  Finished        Mrs. Amy Johny   Madrid

    Age  Designation Level
0    25                  2
1    27                  2
2    29                  3
3    31                  2
4    30                  3
5    27                  1
6    30                  3
7    29                  2
8    25                  2
9    29                  3
10   25                  1
11   31                  2
12   31                  2
13   30                  3

In [16]:
# Task 8 Promote designation level by 1 for the employees whose age is more than 29 years using

# import python libraries
import pandas as pd

Final.loc[Final["Age"] > 29, "Designation Level"] += 1

# Display updated dataframe
print("\nAfter promotion based on age:")
print(Final)

After promotion based on age:
      ID     Project          Cost    Status                  Name     City  \
0   A001   Project 1  1.002000e+06  Finished        Mr. John Alter    Paris
1   A002   Project 2  2.000000e+06   Ongoing  Mrs. Alice Luxemburg   London
2   A003   Project 3  4.500000e+06  Finished     Mr. Tom Sabestine   Berlin
3   A004   Project 4  5.500000e+06   Ongoing       Mrs. Nina Adgra  Newyork
4   A005   Project 5  3.250500e+06  Finished        Mrs. Amy Johny   Madrid
5   A002   Project 6  6.800000e+05    Failed  Mrs. Alice Luxemburg   London
6   A005   Project 7  4.000000e+05  Finished        Mrs. Amy Johny   Madrid
7   A003   Project 8  3.500000e+05    Failed     Mr. Tom Sabestine   Berlin
8   A001   Project 9  2.061714e+06   Ongoing        Mr. John Alter    Paris
9   A003  Project 10  3.000000e+05  Finished     Mr. Tom Sabestine   Berlin
10  A001  Project 11  2.000000e+06    Failed        Mr. John Alter    Paris
11  A004  Project 12  1.000000e+06   Ongoing       Mrs. Nina Adgra  Newyork
12  A004  Project 13  3.000000e+06  Finished       Mrs. Nina Adgra  Newyork
13  A005  Project 14  2.000000e+05  Finished        Mrs. Amy Johny   Madrid

    Age  Designation Level
0    25                  2
1    27                  2
2    29                  3
3    31                  4
4    30                  5
5    27                  1
6    30                  5
7    29                  2
8    25                  2
9    29                  3
10   25                  1
11   31                  4
12   31                  4
13   30                  5

In [17]:
# Task 9 : Total Project Cost per Employee
#import python libraries 
import pandas as pd
#Group by ID and Name, sum cost
TotalProjCost = Final.groupby(["ID", "Name"])["Cost"].sum().reset_index()

# Rename column
TotalProjCost.rename(columns={"Cost": "Total Cost"}, inplace=True)

# Display result
print("\nTotal Project Cost DataFrame:")
print(TotalProjCost)

Total Project Cost DataFrame:
     ID                  Name    Total Cost
0  A001        Mr. John Alter  5.063714e+06
1  A002  Mrs. Alice Luxemburg  2.680000e+06
2  A003     Mr. Tom Sabestine  5.150000e+06
3  A004       Mrs. Nina Adgra  9.500000e+06
4  A005        Mrs. Amy Johny  3.850500e+06

In [20]:
# Task 10:Employees with 'o' in City

#Filter rows where City contains letter 'o'
result = Final[Final["City"].str.contains("o", case=False)]

# Display result
print("\n newemployeedata:")
print(result)

 newemployeedata:
      ID     Project       Cost    Status                  Name     City  Age  \
1   A002   Project 2  2000000.0   Ongoing  Mrs. Alice Luxemburg   London   27
3   A004   Project 4  5500000.0   Ongoing       Mrs. Nina Adgra  Newyork   31
5   A002   Project 6   680000.0    Failed  Mrs. Alice Luxemburg   London   27
11  A004  Project 12  1000000.0   Ongoing       Mrs. Nina Adgra  Newyork   31
12  A004  Project 13  3000000.0  Finished       Mrs. Nina Adgra  Newyork   31

    Designation Level
1                   2
3                   4
5                   1
11                  4
12                  4